branch-defaults:
  master:
    environment: movieapi
    group_suffix: null
global:
  application_name: movie-api
  default_ec2_keyname: null
  default_platform: python2.7
  default_region: us-west-2
  profile: eb-cli
  sc: git
